const productosVarios = [
    {id: 1, nombre: "15 metros de caño de cobre 1/4", tipo: "Para Refrigeracion", cantidad: 1, desc: "Caño de 1/4 para instalacion de aire acondicionado. Nuevo", precio: 16000, talle: "", img:"../imagenes/imgVarios/caño_bronce_varias_medidas.jpg", marca:""},
    {id: 2, nombre: "15 metros de caño de cobre 1/2", tipo: "Para Refrigeracion", cantidad: 1, desc: "Caño de 1/2 para instalacion de aire acondicionado. Nuevo en caja", precio: 28000, talle: "", img:"../imagenes/imgVarios/caño_bronce_varias_medidas.jpg", marca:""},
    {id: 3, nombre: "15 metros de caño de cobre 3/8", tipo: "Para Refrigeracion", cantidad: 1, desc: "Caño de 3/8 para instalacion de aire acondicionado. Nuevo", precio: 23000, talle: "", img:"../imagenes/imgVarios/caño_bronce_varias_medidas.jpg", marca:""},
    {id: 4, nombre: "kit Instalacion aire acondicionado", tipo: "kit para instalacion hasta 4500 fr", cantidad: 1, desc: "3mts caño , aislante, cinta, mensulas, patitas de goma, tornillos, tarugos, manguera de cristal, cable. Nuevo", precio: 18500, talle: "", img:"../imagenes/imgVarios/kit_instalacion_hasta_4500fr.jpeg", marca:""},
    {id: 6, nombre: "Teclado weibo Luminoso", tipo: "kit luminoso", cantidad: 1, desc: "Kit gamer. Teclado y mouse luminosos. Teclado estatico y mouse retro Luminico. Nuevo en caja", precio: 4500, talle: "", img:"../imagenes/imgElectro/Teclado-Weibo.jpeg", marca:"Y47"}
]


    // {id: 4, nombre: "Termometro Digital", tipo: "digital", cantidad: 1, desc: "Color blanco, funciona a pilas. Nuevo en caja", precio: 500, talle: "", img:"../imagenes/imgElectro/termometroDigital.jpeg", marca:"China"},
    // {id: 5, nombre: "Parlante mini", tipo: "Parlante", cantidad: 1, desc: "Colores varios, se conecta con cable, via bluetooth. Nuevo en caja", precio: 500, talle: "", img:"../imagenes/imgElectro/paarlantesMini.jpeg", marca:"China"},
    // {id: 6, nombre: "Balanza de Precision", tipo: "Digital", cantidad: 1, desc: "Color Gris, se carga con cable mini usb. Nuevo en caja", precio: 2000, talle: "", img:"../imagenes/imgElectro/balanzaPrecision.jpeg", marca:"Shirka"},
    // {id: 7, nombre: "Laser larga distancia", tipo: "Led", cantidad: 1, desc: "Color negro, fnciona a pilas. Nuevo en caja", precio: 800, talle: "", img:"../imagenes/imgElectro/laser.jpeg", marca:"China"},
    // {id: 8, nombre: "Auriculares Y47", tipo: "Auricular", cantidad: 1, desc: "Color rosa, se conecta con cable, via Bluetooth. Se carga con mini usb. Nuevo en caja", precio: 2500, talle: "", img:"../imagenes/imgElectro/auricularesY47.jpeg", marca:"Y47"},
    // {id: 10, nombre: "Ekos Encanto Das Flores", tipo: "Peerfume mujer", cantidad: 1, desc: "Nuevo en caja.", precio: 5368, talle: "", img:"../imagenes/imgVarios/EKOS_ENCANTO_DAS_FLORES_$4880.jpeg", marca:"Natura"},
    // {id: 11, nombre: "natura Ekos Preta", tipo: "perfume mujer", cantidad: 1, desc: "Nuevo en caja", precio: 4570, talle: "", img:"../imagenes/imgVarios/natura_Ekos_Preta_$4155.jpeg", marca:"Natura"},
    // {id: 12, nombre: "Natura Tododia", tipo: "perfume mujer", cantidad: 1, desc: "Nuevo en caja", precio: 2970, talle: "", img:"../imagenes/imgVarios/Natura_Tododia_$2700.jpeg", marca:"Natura"},
    // {id: 13, nombre: "natura homem reconecta", tipo: "perfume mujere", cantidad: 1, desc: "Nuevo en caja", precio: 2013, talle: "", img:"../imagenes/imgVarios/natura_homem_reconecta_$1830.jpeg", marca:"Natura"},