const productosElectro = [
    {id: 1, nombre: "Split BGH silent Air On-Off 2300 Fr.", tipo: "Aire Acondicionado", cantidad: 1, desc: "Split BGH silent Air On-Off 2300 Fr. Nuevo", precio: 705000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_silent_air_on-off_2300.jpeg", marca:"BGH/jose"},
    {id: 2, nombre: "Split BGH Silent Air On-Off 3000 Fr.", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH silent Air On-Off 3000 Fr. Nuevo", precio: 743000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_silent_air_on-off_3000.jpeg", marca:"BGH/jose"},
    {id: 3, nombre: "Split BGH Silent Air On-Off 4500 Fr", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH silent Air On-Off 4500 Fr. Nuevo", precio: 1020000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_silent_air_on-off_4500.webp", marca:"BGH/jose"},
    {id: 4, nombre: "Split BGH Silent Air On-Off 5500 Fr", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH silent Air On-Off 5500 Fr. Nuevo", precio: 1275000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_silent_air_on-off_5500.jpg", marca:"BGH/jose"},
    {id: 5, nombre: "Split BGH Silent Air On-Off 8000 whats", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH Silent Air On-Off 8000 whats. Nuevo", precio: 1338000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_silent_air_on-off_8000_whats.webp", marca:"BGH/jose"},
    {id: 6, nombre: "Split BGH cooltime on-off 2300 fr, frio/calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH cooltime on-off 2300 fr frio/calor. Nuevo", precio: 706000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_cooltime_on-off_2300_f-c.png", marca:"BGH/jose"},
    {id: 7, nombre: "Split BGH cooltime on-off 3000 fr, frio/calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH cooltime on-off 3000 fr, frio-calor. Nuevo", precio: 720000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_cooltime_on-off_3000_f-c.png", marca:"BGH/jose"},
    {id: 8, nombre: "Split BGH cooltime on-off 4500 fr, frio/calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH cooltime on-off 4500 fr, frio/calor. Nuevo", precio: 998000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_cooltime_on-off_4500_f-c.png", marca:"BGH/jose"},
    {id: 9, nombre: "Split BGH cooltime on-off 5500 fr, frio/calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH cooltime on-off 5500 fr, frio/calor. Nuevo", precio: 1275000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_cooltime_on-off_5500_f-c.png", marca:"BGH/jose"},
    {id: 10, nombre: "Split BGH Inverter 3000 fr", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH Inverter 3000 fr. Nuevo", precio: 815000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_inverter_3000.webp", marca:"BGH/jose"},
    {id: 11, nombre: "Split BGH Inverter 4500 fr", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH Inverter 4500 fr. Nuevo", precio: 1190000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_inverter_4500.webp", marca:"BGH/jose"},
    {id: 12, nombre: "Split BGH Inverter 5500 fr", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH Inverter 5500 fr. Nuevo", precio: 1480000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_inverter_5500.jpg", marca:"BGH/jose"},
    {id: 13, nombre: "Split BGH Cooltime Inverter 3000fr Frio-Calor", tipo: "Aire Acondicionado", cantidad: 1, desc: "Nuevo. Split BGH Cooltime Inverter 3000fr Frio-Calor", precio: 865000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_cooltime_inverter_4500_f-c.png", marca:"BGH/jose"},
    {id: 14, nombre: "Split BGH Cooltime Inverter 4500fr Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH Cooltime Inverter 4500fr Frio-Calor. Nuevo", precio: 1120000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_cooltime_inverter_4500_f-c.png", marca:"BGH/jose"},
    {id: 15, nombre: "Split BGH Cooltime Inverter 5500fr Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split BGH Cooltime Inverter 5500fr Frio-Calor. Nuevo", precio: 1410000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_bgh_cooltime_inverter_5500_f-c.jpg", marca:"BGH/jose"},
    {id: 16, nombre: "Split LG Dual cool wifi Inverter 3000 fr. Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split LG Dual cool wifi Inverter 3000 fr. Frio-Calor. Nuevo", precio: 1035000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_lg_dualcool_wifi_inverter_3000_f-c.jpg", marca:"LG/jose"},
    {id: 17, nombre: "Split LG Dual cool wifi Inverter 4500 fr. Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split LG Dual cool wifi Inverter 4500 fr. Frio-Calor. Nuevo en caja", precio: 1480000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_lg_dualcool_wifi_inverter_4500_f-c.jpg", marca:"LG/jose"},    
    {id: 18, nombre: "Split LG Dual cool wifi Inverter 6000 fr. Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split LG Dual cool wifi Inverter 6000 fr. Frio-Calor. Nuevo en caja", precio: 1690000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_lg_dualcool_wifi_inverter_6000_f-c.png", marca:"LG/jose"},
    {id: 19, nombre: "Split LG Art cool Inverter 3000 fr. Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split LG Art cool Inverter 3000 fr. Frio-Calor. Nuevo en caja", precio: 1175000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_lg_artcool_inverter_3000_f-c.jpg", marca:"LG/jose"},
    {id: 20, nombre: "Split LG Art cool Inverter 4500 fr. Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split LG Art cool Inverter 4500 fr. Frio-Calor. Nuevo en caja", precio: 1655000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_lg_artcool_inverter_4500_f-c.jpg", marca:"LG/jose"},
    {id: 21, nombre: "Split LG Art cool Inverter 6000 fr. Frio-Calor", tipo: "Aire acondicionado", cantidad: 1, desc: "Split LG Art cool Inverter 6000 fr. Frio-Calor. Nuevo en caja", precio: 1970000, talle: "", img:"../imagenes/imgElectro/imgAAAA/split_lg_artcool_inverter_6000_f-c.jpg", marca:"LG/jose"},
    {id: 22, nombre: "300 mbps High Power Wireless usb Adapter", tipo: "Adaptador Antena Wifi de 300 mbps", cantidad: 1, desc: "Color Gris, se carga con cable mini usb. Nuevo en caja", precio: 20000, talle: "", img:"../imagenes/imgElectro/300mbps_High_Power_Wireless_usb_Adapter.webp", marca:"Salta_2025"},
    {id: 23, nombre: "Sartén multicocina eléctrica Suono", tipo: "Electronico de cocina", cantidad: 1, desc: "*Potencia: 1350w. *Material: Antiadherente. *Material tapa: Vidrio templado. *Temperatura: 5 Niveles Ajustables. *Voltaje: 220v - 250v.", precio: 48000, talle: "", img:"../imagenes/imgElectro/Sartén_multicocina_electrica_Suono.jpeg", marca:"Leichu"},
    {id: 24, nombre: "Patillera Profesional Vintage T9 Dragon Suono", tipo: "Cortadora de pelo", cantidad: 1, desc: "*Voltaje 3v. *La cuchilla posee cabeza redondeada, y pequeños dientes de 0,4 a 0,8mm. *4 peines intercambiables de 1.5, 2, 3 y 4. *Bateria Recargable. Tiempo de carga 2hs. Incluye todos los accesorios necesarios para un kit que puede ir desde amateur hasta profesional.", precio: 17000, talle: "", img:"../imagenes/imgElectro/Patillera_profeional_vintage_t9_dragon_Suono.jpeg", marca:"Leichu"},
    {id: 25, nombre: "Auricular Inalambricos Cart Ear celeste Suono (P47)", tipo: "Auriculares Musica", cantidad: 1, desc: "*Soporte tarjeta FT. *Bateria Recargable via USB. *Micrófono. *Botones de control. *Altamente eficiente en transmisión. *Luz de 7 colores.", precio: 11000, talle: "", img:"../imagenes/imgElectro/Auriculares_inalambricos_Cat_Ear.jpeg", marca:"Leichu"}





]

