const productosIndu = [
    {id: 1, nombre: "Zapatillas Adidas Lightmotion", tipo: "zapatillas", cantidad: 1, desc: "Nueva talle '10.5', color gris,", precio: 105000, talle: "10.5", img:"../imagenes/imgIndumentaria/adidas_lightmotion_jotita.jpeg", marca:"ADIDAS"},
    {id: 2, nombre: "Buzo Essentials", tipo: "Buzo", cantidad: 1, desc: "Color Gris Topo, Nueva talle 'M'", precio: 185000, talle: "M", img:"../imagenes/imgIndumentaria/buzo_essentials_fear_of_god_jotita.jpeg", marca:"Essentials"},
    {id: 3, nombre: "Buzo Adidas", tipo: "Buzo", cantidad: 1, desc: "Color Negro. con capucha. Nuevo talle 'XL'", precio: 180000, talle: "XL", img:"../imagenes/imgIndumentaria/buzo_adidas_canguro_jotita.jpeg", marca:"ADIDAS"},
    {id: 4, nombre: "Campera Jordan", tipo: "Campera", cantidad: 1, desc: "Color Negro. Nuevo Talle 'M'", precio: 255000, talle: "M", img:"../imagenes/imgIndumentaria/campera_jordan_23_jotita.jpeg", marca:"JORDAN"},
    {id: 5, nombre: "Buzo Nike", tipo: "Buzo", cantidad: 1, desc: "Buzo con capucha , bolsillo en manga, color verde agua, bolsillo al frente. Talle XL", precio: 185000, talle: "XL", img:"../imagenes/imgIndumentaria/buzo_canguro_capucha_nike.jpeg", marca:"NIKE"},
    {id: 6, nombre: "Air Jordan Retro 4", tipo: "Zapatillas", cantidad: 1, desc: "Nuevo. Zapatillas color Negro y amarillo. Talle 10us", precio: 455000, talle: "10us", img:"../imagenes/imgIndumentaria/Air_jordan_retro_4_thunder_jotita.jpeg", marca:"JORDAN"},
    {id: 7, nombre: "Nike Air Jordan 2 Retro OG Chicago", tipo: "Zapatillas", cantidad: 1, desc: "Color Blanco . Nueva. Talle : '10us'", precio: 355000, talle: "10us", img:"../imagenes/imgIndumentaria/nike_air_jordan_2_retro_og_chicago_jotita.jpeg", marca:"JORDAN"},
    {id: 8, nombre: "Riñoneras Air Jordan", tipo: "Prendas", cantidad: 1, desc: "Color Negro , Blanco y Rojo. Nuevas.", precio: 80000, talle: "??", img:"../imagenes/imgIndumentaria/riñoneras_air_jordan_jotita.jpeg", marca:"Air Jordan"},
    {id: 9, nombre: "Ojotas Mercedes Benz", tipo: "Calzado", cantidad: 1, desc: "Color Negras. Nueva. Talle : '10us'", precio: 90000, talle: "10us", img:"../imagenes/imgIndumentaria/ojotas_mercedes_benz_petronas_jotita.jpeg", marca:"Mercedes Benz"},
    {id: 10, nombre: "Nike Air Max", tipo: "Calzado", cantidad: 1, desc: "Color rojo. Nueva. Talle : '9.5us'", precio: 255000, talle: "9.5", img:"../imagenes/imgIndumentaria/nike_air_max_90_sp_jotita.jpeg", marca:"NIKE"},
    {id: 11, nombre: "Gorra Mercedez", tipo: "Gorra", cantidad: 1, desc: "Nueva. Gorra Mercedez Benz. color Azul", precio: 45000, talle: "Unico", img:"../imagenes/imgIndumentaria/gorra_1.jpeg", marca:"Jotita"},
    {id: 12, nombre: "Campera Champion", tipo: "Campera", cantidad: 1, desc: "Campera con capucha bolsillos. Color Negro. Nueva. Talle : 'M'", precio: 90000, talle: "M", img:"../imagenes/imgIndumentaria/campera_capucha_champions_jotita.jpeg", marca:"CHAMPION"},
    {id: 13, nombre: "Short Nike", tipo: "Short", cantidad: 1, desc: "Color negro y blanco. Nuevo. Talles : 'M'y'XL'", precio: 70000, talle: "M,XL", img:"../imagenes/imgIndumentaria/short_nike_jotita.jpeg", marca:"NIKE"},
    {id: 14, nombre: "Short Jordan", tipo: "Short", cantidad: 1, desc: "Color gris con naraja. Nuevo. Talle : 'XL'", precio: 90000, talle: "XL", img:"../imagenes/imgIndumentaria/short_jordan_jotita.jpeg", marca:"JORDAN"},
    {id: 15, nombre: "Short Nike de Baño", tipo: "Short", cantidad: 1, desc: "Color Verde. Nuevo. Talle : 'XL'", precio: 85000, talle: "XL", img:"../imagenes/imgIndumentaria/short_nike_baño_jotita.jpeg", marca:"NIKE"},
    {id: 16, nombre: "Short", tipo: "Short", cantidad: 1, desc: "Color Negro y Blanco. Nuevo. Talle : 'L'", precio: 95000, talle: "L", img:"../imagenes/imgIndumentaria/shot_bcongro_jotita.jpeg", marca:"??"},
    {id: 17, nombre: "Short Nike Azul", tipo: "Short", cantidad: 1, desc: "Color Azul. Nuevo . Nike Talle : 'M'", precio: 70000, talle: "M", img:"../imagenes/imgIndumentaria/shot_bcongro_jotita.jpeg", marca:"NIKE"},
    {id: 18, nombre: "Pantalon Gris Nike", tipo: "Pantalon", cantidad: 1, desc: "Color Gris ,bolsillos. Nuevo. Talle : 'M'", precio: 120000, talle: "M", img:"../imagenes/imgIndumentaria/pantalon_nike_gris_jotita.jpeg", marca:"NIKE"},
    {id: 19, nombre: "Short GS Nike", tipo: "Short", cantidad: 1, desc: "Color Morado y negro. Talle : 'L' ", precio: 115000, talle: "L", img:"../imagenes/imgIndumentaria/Nike_Lebron_James_Space_Jam_Legacy_Goon_Squad_jotita.jpeg", marca:"NIKE"}
]



//  agregar productos
//{id: 20, nombre: "Panchas", tipo: "Calzado", cantidad: 1, desc: "Color Marrones. Nuevas. Varios Talles. consultar por talles y precios", precio: 2500, talle: "varios", img:"../imagenes/imgIndumentaria/Panchas-marrones.jpeg", marca:"Pamela"},
//{id: 21, nombre: "Panchas", tipo: "Calzado", cantidad: 1, desc: "Color Marron. Nuevas. Varios Talles. consultar por talles y precios", precio: 2500, talle: "varios", img:"../imagenes/imgIndumentaria/Panchas-marronesLateral.jpeg", marca:"Pamela"},
//{id: 22, nombre: "Panchas Tiritas", tipo: "Calzado", cantidad: 1, desc: "Colores varios. Nuevas. Varios Talles. consultar por talles y precios", precio: 2500, talle: "varios", img:"../imagenes/imgIndumentaria/Panchas-TiritasLateral.jpeg", marca:"Pamela"},
//{id: 23, nombre: "Panchas Tiritas", tipo: "Calzado", cantidad: 1, desc: "Varios Colores. Nuevas. Varios Talles. consultar por talles y precios", precio: 2500, talle: "varios", img:"../imagenes/imgIndumentaria/Panchas-Tiritas.jpeg", marca:"Pamela"},
//{id: 24, nombre: "Panchas", tipo: "Calzado", cantidad: 1, desc: "Varios Colores. Nuevas. Varios Talles. consultar por talles y precios", precio: 2500, talle: "varios", img:"../imagenes/imgIndumentaria/Panchas-verdesLateral.jpeg", marca:"Pamela"},
//{id: 25, nombre: "Camiseta Titular Argentina", tipo: "Remera", cantidad: 1, desc: "Camiseta de la ^^Seleccion Argentina 2022. Celeste y Blanca, estampada Numero 5 Paredes", precio: 4000, talle: "varios", img:"../imagenes/imgIndumentaria/PatoIndu-CamisetaTitularSeleccionArg5.jpeg", marca:"Patoindu"},
//{id: 26, nombre: "Remerita de tiritas", tipo: "Remera", cantidad: 1, desc: "Color rosa. Nuevo. Talle : '2'", precio: 500, talle: "2", img:"../imagenes/imgIndumentaria/remeritaTiritas_Ingrid.jpeg", marca:"??"}